//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTASaveData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GTASaveData.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sequence length must be less than or equal to the length of the array..
        /// </summary>
        public static string Error_Argument_SequenceTooBig {
            get {
                return ResourceManager.GetString("Error_Argument_SequenceTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The index is out of range..
        /// </summary>
        public static string Error_ArgumentOutOfRange_IndexOutOfRange {
            get {
                return ResourceManager.GetString("Error_ArgumentOutOfRange_IndexOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of stream reached..
        /// </summary>
        public static string Error_EndOfStream {
            get {
                return ResourceManager.GetString("Error_EndOfStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection cannot be modified while being changed by another thread..
        /// </summary>
        public static string Error_InvalidOperation_NoCollectionReentrancy {
            get {
                return ResourceManager.GetString("Error_InvalidOperation_NoCollectionReentrancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size not defined for type &apos;{0}&apos;..
        /// </summary>
        public static string Error_InvalidOperation_SizeNotDefined {
            get {
                return ResourceManager.GetString("Error_InvalidOperation_SizeNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected end of stream reached while parsing JSON..
        /// </summary>
        public static string Error_JsonSerialization_EndOfStream {
            get {
                return ResourceManager.GetString("Error_JsonSerialization_EndOfStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected token while parsing JSON: {0}.
        /// </summary>
        public static string Error_JsonSerialization_UnexpectedToken {
            get {
                return ResourceManager.GetString("Error_JsonSerialization_UnexpectedToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first item in the ped pool must be a PlayerPed..
        /// </summary>
        public static string Error_PlayerNotFound {
            get {
                return ResourceManager.GetString("Error_PlayerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad block size: {0}.
        /// </summary>
        public static string Error_Serialization_BadBlockSize {
            get {
                return ResourceManager.GetString("Error_Serialization_BadBlockSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; cannot be pre-allocated..
        /// </summary>
        public static string Error_Serialization_NoPreAlloc {
            get {
                return ResourceManager.GetString("Error_Serialization_NoPreAlloc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; does not support serialization..
        /// </summary>
        public static string Error_SerializationNotAllowed {
            get {
                return ResourceManager.GetString("Error_SerializationNotAllowed", resourceCulture);
            }
        }
    }
}
